name: Portfolio CI

on:
  push:
    branches:
      - main

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files
        run: ls -la

      - name: Success Message
        run: echo "Portfolio Build Successful 🚀"
